# Generated by Django 5.0.3 on 2024-04-23 11:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0003_color_gender_cat_age_alter_cat_author_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cat',
            options={'ordering': ['-pk'], 'verbose_name': 'Cat', 'verbose_name_plural': 'Cats'},
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='users/')),
                ('phone', models.CharField(blank=True, max_length=13, null=True, verbose_name='Phone number')),
                ('mobile', models.CharField(blank=True, max_length=13, null=True, verbose_name='Mobile')),
                ('email', models.EmailField(max_length=50, verbose_name='Email')),
                ('site', models.URLField(blank=True, max_length=50, null=True)),
                ('github', models.CharField(blank=True, max_length=50, null=True)),
                ('telegram', models.CharField(blank=True, max_length=50, null=True)),
                ('instagram', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
            options={
                'verbose_name': 'Custom user',
                'verbose_name_plural': 'Custom users',
                'ordering': ['-pk'],
            },
        ),
    ]
