# Generated by Django 5.0.3 on 2024-04-23 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cat', '0004_alter_cat_options_customuser'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='github',
            new_name='address',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='instagram',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='customuser',
            old_name='telegram',
            new_name='job2',
        ),
    ]
